### ISSUE TITLE
TransitionGroup for single component

### ISSUE THREAD

**Issue by atwaves** [infernojs/inferno-transition-group#1]
Hello. How to create single transitioned component like this:

[https://codepen.io/artemxgruden/pen/ygvvZr](https://codepen.io/artemxgruden/pen/ygvvZr)

In reactTransitionGroup it available via

    FirstChild( props ) {
        const childrenArray = React.Children.toArray( props.children )
        return childrenArray[0] || null
    }

`<ReactTransitionGroup component={ this.FirstChild }>
<Single  />
</ReactTransitionGroup>`

please help

**Comment by Havunen** [comment]
Hi @atwaves thanks for reporting this issue. I will have a look today / tommorow

**Comment by atwaves** [comment]
@Havunen Hi, what's new?

**Comment by Havunen** [comment]
Sorry I have been traveling lately and was not able to have a look at this.

**Comment by joshwcomeau** [comment]
EDIT: Actually, while this works in terms of mounting/unmounting, it does not appear to be calling the added lifecycle methods (`componentWillEnter` / `componentWillLeave`)... So yeah this isn't really a solution.

----

I also needed to wrap a single child in `<InfernoTransitionGroup>`.

The default behaviour appears to be broken. Example:

```js
// Assume `showElement` is a boolean prop that will change when we want to toggle the content

<InfernoTransitionGroup>
  {showElement && <MyCustomComponent key="yep" />
</InfernoTransitionGroup>
```

Sadly, this example won't work: When the boolean prop changes, the children rendered by InfernoTransitionGroup doesn't change.

I haven't been able to figure out why, but I did come up with a workaround:

```js
const FirstChild = ({ children }) => (
  Array.isArray(children) ? children[0] : children
);

<InfernoTransitionGroup component={FirstChild}>
  {showElement && <MyCustomComponent key="yep" />
</InfernoTransitionGroup>
```

This is a modified example from the ReactTransitionGroup docs. Since Inferno does not provide Children helpers, I wrote a very basic one.

Note that I'm not sure how robust this solution is; it works for me, but be sure to test it within your own code.

**Comment by sprlwrksAprilmintacpineda** [comment]
the docs at https://reactjs.org/docs/animation.html#animating-one-or-zero-items explains that this can be done through:

```jsx
<div>
  <ReactCSSTransitionGroup
    transitionName="carousel"
    transitionEnterTimeout={300}
    transitionLeaveTimeout={300}>
    <img src={props.imageSrc} key={props.imageSrc} />
  </ReactCSSTransitionGroup>
</div>
```

But when I tried it with this library, it doesn't seem to work.

```jsx
<InfernoTransitionGroup
  transitionName="slide"
  transitionEnterTimeout={500}
  transitionLeaveTimeout={500}>
  { this.state.rightSideBar.isOpen? <RightSideBar key="abc" /> : null }
</InfernoTransitionGroup>
```

a workaround:

```jsx
<InfernoTransitionGroup
   transitionName="slide"
   transitionEnterTimeout={500}
   transitionLeaveTimeout={500}
  component={({ children }) => children}>
      { this.state.rightSideBar.isOpen? <RightSideBar /> : null }
</InfernoTransitionGroup>
```
